name: build-minor

on:
  schedule: [cron: '10 * * * *'] # every 1 hour
  push:
    branches: [master, main]
    tags-ignore: ['**']

jobs:
  plan:
    name: Generate the build matrix
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.result }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/github-script@v6
        id: set-matrix
        with:
          github-token: 'empty' # the token is not needed for the script running
          script: return await require('./.github/scripts/generate-minor-node-matrix.js')({github, context, core})
        env:
          source-image: library/node
          target-image: tarampampam/node

  build:
    name: Build the docker image (${{ matrix.tag }})
    needs: [plan]
    if: ${{ fromJSON(needs.plan.outputs.matrix).include[0] }} # docs: <https://bit.ly/2YHHXXs>
    runs-on: ubuntu-20.04
    #timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.plan.outputs.matrix) }}
      #  include:
      #    - {tag: foo, platforms: 'platform/one,platform/two/v2'}
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3 # Action page: <https://github.com/docker/build-push-action>
        with:
          context: .
          file: Dockerfile
          push: true # comment this line for the local workflow running
          platforms: ${{ matrix.platforms }}
          build-args: "NODE_VERSION=${{ matrix.tag }}"
          tags: |
            tarampampam/node:${{ matrix.tag }}
            ghcr.io/${{ github.actor }}/node:${{ matrix.tag }}
