name: documentation

on:
  push:
    branches: [master, main]
    tags-ignore: ['**']

jobs:
  docker-hub-description:
    name: Docker Hub Description
    runs-on: ubuntu-20.04
    steps:
      - uses: peter-evans/dockerhub-description@v2 # Action page: <https://github.com/peter-evans/dockerhub-description>
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tarampampam/node
