name: tests

on:
  push:
    branches: [master, main]
    tags-ignore: ['**']
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs: # Docs: <https://git.io/JvxXE>
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}

      - uses: zricethezav/gitleaks-action@v1 # Action page: <https://github.com/zricethezav/gitleaks-action>

  docker-image:
    name: Build docker image
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: ['', alpine, latest]
    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v2 # Action page: <https://github.com/docker/build-push-action>
        with:
          context: .
          file: Dockerfile
          push: false
          build-args: "NODE_VERSION=${{ matrix.node-version }}"
          tags: node:ci

      - uses: anchore/scan-action@v3 # action page: <https://github.com/anchore/scan-action>
        with:
          image: node:ci
          fail-build: false
          severity-cutoff: high # negligible, low, medium, high or critical
