name: tests

on:
  push:
    branches: [master, main]
    tags-ignore: ['**']
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs: # Docs: <https://git.io/JvxXE>
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with: {fetch-depth: 0}

      - name: Check for GitLeaks
        uses: gacts/gitleaks@v1 # Action page: <https://github.com/gacts/gitleaks>

  build:
    name: Build the docker image
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: ['', alpine, latest, 6.17-alpine, 8.12-alpine]
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v3 # Action page: <https://github.com/docker/build-push-action>
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          file: Dockerfile
          push: false
          build-args: "NODE_VERSION=${{ matrix.node-version }}"
          tags: node:ci
